### PR TITLE
Removal of myself from CODEOWNERS

### PR DESCRIPTION
**Pull request by HazWard**
**What this PR does / Why we need it**:
Removal of myself from CODEOWNERS since I no longer actively participate in the community.

**Which issue(s) this PR fixes**:

N/A

**Special notes for your reviewer**:
Thank you for letting be a part of this awesome project!

### CODE REVIEW

**Review by joeholley — APPROVED** [review]
LGTM

**Comment by HazWard** [comment]
I think only a Google employee can have access to the Cloud Build failure.

**Comment by govargo** [comment]
@HazWard 
Hi, there was the Cloud Build error in our document.
I fixed the build error by https://github.com/googleforgames/open-match/pull/1765.

Could you rebase to latest?

Thank you.

**Comment by govargo** [comment]
/gcbrun
for re-test

**Comment by govargo** [comment]
Thank you for your contribution for a long time.

**Comment by HazWard** [comment]
> Thank you for your contribution for a long time.

It has been a pleasure!

**Pull request merged**
