### PR TITLE
Update to gRPC Gateway v2

### PR DESCRIPTION
**Pull request by andrewgrundy**
**What this PR does / Why we need it**:
Updates gRPC-Gateway to the latest version, following the migration path detailed here: 
  https://grpc-ecosystem.github.io/grpc-gateway/docs/development/grpc-gateway_v2_migration_guide/

**Special notes for your reviewer**:
I have set the flags and options required to keep the API generated by the gateway as close to the output of v1 as possible.

### CODE REVIEW

**Comment by thisisnotapril** [comment]
@andrewgrundy did my rerun work?

**Comment by andrewgrundy** [comment]
@thisisnotapril yeah, all checks pass. It just needs to be reviewed, approved and merged now :)

**Comment by syntxerror** [comment]
@andrewgrundy hey can you do a merge to bring this up to date with master? I had to update my username to be added as a reviewer. I should be able to merge once you've done that

**Review by syntxerror — APPROVED** [review]
LGTM

**Pull request merged**
