### PR TITLE
Add annotation settings to frontend Service helm for `aws-load-balancer-controller`

### LINKED ISSUE #1441: Add annotation settings for frontend Service helm
**Is your feature request related to a problem? Please describe.**
I try to use open-match with AWS EKS.
In AWS EKS,  `aws-load-balancer-controller` is needed using AWS LB(ALB or NLB) for k8s Service.
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/guide/service/annotations/
Using`aws-load-balancer-controller`, need some annotations for Service.

But, no annotaion options for frontend Service.
https://github.com/googleforgames/open-match/blob/main/install/helm/open-match/templates/frontend.yaml#L21 .

**Describe the solution you'd like**
Add `frontend.service.annotations` settings for Helm.
And apply `frontend.service.annotations` to frontend.yaml like below.

```diff
--- a/install/helm/open-match/templates/frontend.yaml
+++ b/install/helm/open-match/templates/frontend.yaml
@@ -18,7 +18,13 @@ apiVersion: v1
 metadata:
   name: {{ include "openmatch.frontend.hostName" . }}
   namespace: {{ .Release.Namespace }}
-  annotations: {{- include "openmatch.chartmeta" . | nindent 4 }}
+  annotations:
+    {{- include "openmatch.chartmeta" . | nindent 4 }}
+    {{- if .Values.frontend.service.annotations }}
+    {{- range $key, $value := .Values.frontend.service.annotations }}
+    {{ $key }}: {{ $value | quote }}
+    {{- end }}
+    {{- end }}
   labels:
     app: {{ template "openmatch.name" . }}
     component: frontend
```

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by SpringMT**
**What this PR does / Why we need it**:
I try to use open-match with AWS EKS.
In AWS EKS,  `aws-load-balancer-controller` is needed using AWS LB(ALB or NLB) for k8s Service.
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/guide/service/annotations/
Using`aws-load-balancer-controller`, need some annotations for Service.

But, no annotaion options for frontend Service.
https://github.com/googleforgames/open-match/blob/main/install/helm/open-match/templates/frontend.yaml#L21 .

So, add `frontend.service.annotations` settings for Helm.

**Which issue(s) this PR fixes**:

Closes #1441 

**Special notes for your reviewer**:

### CODE REVIEW

**Review by syntxerror — APPROVED** [review]
LGTM

**Comment by syntxerror** [comment]
Thanks for submitting the PR for this!

**Comment by mridulji** [comment]
Could you please sign the CLA and let  us know if facing any difficulty.

**Comment by SpringMT** [comment]
I signed the CLA.

**Comment by mridulji** [comment]
Ah! I see, if you rebase your local branch to repo's main branch and then force push it then this CLA issue will be fixed.

**Comment by Jendoliver** [comment]
Hi! I'm interested in this exact feature, is there anything I could do to get traction on it again? I can reopen the same PR but didn't want to do it straight away without asking first, in case you'd prefer to do it in another way. Thanks!

**Pull request closed without merging**
