### PR TITLE
arm64 toolchain support

### PR DESCRIPTION
**Pull request by castaneai**
**What this PR does / Why we need it**:

Upgrade the toolchains to support development on arm64 machines.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by castaneai** [comment]
To prevent large PRs, we would like to break them up into multiple PRs.

**Comment by syntxerror** [comment]
Yeah agreed. There was A LOT of good changes here and likely would be easier to track them individually. I will say the update to Go 1.19 may require some additional changes and and update to Protobuf which can be seen in #1444. Thanks for this and looking forward to the PR's

**Comment by castaneai** [comment]
Thanks for the re-opening, I have pushed the code again. However, I do not have permission to see the log of Cloud Build failures.

**Comment by mridulji** [comment]
Please join [open-match-discuss](https://groups.google.com/forum/#!forum/open-match-discuss) group and then try to see cloud-build logs in sometime.

**Comment by mridulji** [comment]
Hi @castaneai, please let me know if you need help on this.

**Comment by castaneai** [comment]
@mridulji Thanks for your help!
Cloud Build logs show no connection to the Kubernetes cluster endpoint in the helm-chart testing step. do you know how they create kubernetes clusters on CI?

**Comment by mridulji** [comment]
> Cloud Build logs show no connection to the Kubernetes cluster endpoint in the helm-chart testing step. 

To test the changes, Have you used `make presubmit` command. I think `yamale` needs to be added in the `build/toolchain/...` commands in makefile. 

`Note: Please feel free to remove test keyword from presubmit command temporarily if e2e tests fails`

> do you know how they create kubernetes clusters on CI?

The cluster `open-match-ci` is already in place and re-used in every CI build.

**Comment by castaneai** [comment]
Thanks for your help.
I am testing "make lint-chart" with minikube. I have applied some patches for minikube.

However, when I run install-and-lint with chart-testing, I still seem to lose communication to the kubernetes cluster, it happens in Cloud Build and I can reproduce it in my minikube, but I don't know the cause yet.

```
	 Linting chart "open-match => (version: \"0.0.0-dev\", path: \"/workspace/install/helm/open-match\")"
  Validating /workspace/install/helm/open-match/Chart.yaml...
  Validation success! 👍
  ==> Linting /workspace/install/helm/open-match
  
  1 chart(s) linted, 0 chart(s) failed
  Installing chart "open-match => (version: \"0.0.0-dev\", path: \"/workspace/install/helm/open-match\")"...
  Creating namespace "open-match-1oqkwkie35"...
  The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

**Comment by mridulji** [comment]
Could you please help us with the reproduction steps? As I am not able reproduce it in local, but yes I see in CI build.

**Pull request closed without merging**
