### PR TITLE
Bump protobuf to v1.34.1

### PR DESCRIPTION
**Pull request by govargo**
**What this PR does / Why we need it**:

This PR bump protobuf version to reduce security risk according to dependabot.

**Which issue(s) this PR fixes**:

Closes #1718

**Special notes for your reviewer**:

None

### CODE REVIEW

**Comment by govargo** [comment]
@joeholley @kazshinohara @kemurayama
Could you review this?

**Comment by govargo** [comment]
@kemurayama 
Thanks. I updated and rebased this branch.

**Comment by govargo** [comment]
It seems that `2: Test: Markdown` of CI failed. I'll fix this by another PR.
Please wait until the new PR.

**Comment by govargo** [comment]
@kemurayama 
Rebased to the latest.
Ready for review.

**Review by kemurayama — APPROVED** [review]
LGTM

**Pull request merged**
