### PR TITLE
release-1.1.0-rc.1

### PR DESCRIPTION
**Pull request by jonfoust**
**Special notes for your reviewer**:
This PR uses files that may need to be merged via #1283

### CODE REVIEW

**Comment by Laremere** [comment]
Hey, shouldn't this be 1.0.0-rc.1?

**Comment by jonfoust** [comment]
I updated to 1.1.0-rc.1 which I think is right. Yes?

**Comment by Laremere** [comment]
Ah, sorry, you're right.  My problem isn't the title, but the values: https://github.com/googleforgames/open-match/pull/1218/files

**Comment by jonfoust** [comment]
Ahhh I see. Will make the update shortly

**Review by Laremere — APPROVED** [review]

**Pull request merged**
