### PR TITLE
Respond to AcknowledgeBackfill with the tickets that were assigned

### LINKED ISSUE #1381: Add Tickets that were acknowledged to the response from AcknowledgeBackfill
**Is your feature request related to a problem? Please describe.**

When acknowledging a backfill to assign tickets to it, the assigner (the caller of AcknowledgeBackfill) never gets a list of tickets that were successfully acknowledged. 

**Describe the solution you'd like**

A list of tickets associated with the backfill to be returned from AcknowledgeBackfill.

**Describe alternatives you've considered**

A hacky self-made tracking method that can break in many ways.

**Additional context**

Not getting a list of tickets that were successfully assigned breaks with the model of how Assigning works because the normal Assignment process has an explicit list of failures and an implicit list of successes (each requested ticket that was not on the failure list). In Backfill Ack Assignment, there is an indefinite (but bounded) amount of time between the FetchMatches call completing and the AcknowledgeBackfill call starting. This means that tickets could be cancelled in that time, reducing the set from what FetchMatches returned. It is also valuable to be able to acquire the ticket data from the acknowledging party to consume data that was stored in the Extensions of the tickets.

### PR DESCRIPTION
**Pull request by highlyunavailable**
**What this PR does / Why we need it**:

When acknowledging a backfill to assign tickets to it, the assigner (the caller of AcknowledgeBackfill) never gets a list of tickets that were successfully acknowledged. This PR resolves that and closes the loop to allow the caller of AcknowledgeBackfill to see data from tickets that got an assignment as part of AcknowledgeBackfill.

**Which issue(s) this PR fixes**:

Closes #1381

**Special notes for your reviewer**:

This is a "breaking" change insofar as the response type of AcknowledgeBackfill has changed.

### CODE REVIEW

**Comment by scosgrave** [comment]
Thanks for making this change, it was definitely needed. We discussed this in a meeting, and I think I was supposed to make an issue for it, but never got to it. See: https://github.com/googleforgames/open-match/discussions/1360.

Code changes look good to me. Do we need an update to the online docs as well?

**Comment by highlyunavailable** [comment]
Point me to where I'd need to update and I'll happily add a PR for the docs! Do proto docs get auto-generated or do I need to pull the changes in somewhere?

**Review by andrewgrundy — APPROVED** [review]

**Comment by HazWard** [comment]
The docs repo is [here](https://github.com/googleforgames/open-match-docs) but I'm not too sure how the proto docs get generated.

**Comment by highlyunavailable** [comment]
@scosgrave I have created updated documentation and referenced the "Tickets" field in https://github.com/googleforgames/open-match-docs/pull/229

**Review by syntxerror — APPROVED** [review]
LGTM

**Pull request merged**
